name: module3_task1

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight UTC

jobs:
  validate:https://students-support.hbtn.io/hc
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Makefile
        run: cd ./module3_task1/ && make help

      - name: build
        run: |
          pwd && ls
          sudo ./setup.sh
          
      - name: make-help
        run: |
          make help
          
      - name: make-build
        run: |
          make build
          
      - name: make-post
        run: |
          make POST_NAME=who-are-we POST_TITLE="Who are we" post
          
      - name: make-clean
        run: |
          make clean
          ls
